  **PyTorch Fundamentals
  Resorch Notebook:**
  http://www.learnpytorch.io/00_pytorch_fundamentals/


**Questions:** http://github.com/mrdbourke/pytorch-deep-learning/discussions


In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.4.1


### checking cuda is available or not 

In [46]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [47]:
 scalar.ndim

0

In [48]:
scalar.item()

7

In [49]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [50]:
vector.ndim

1

In [51]:
# Check shape of vector
vector.shape

torch.Size([2])

In [52]:
#MATRIX
MATRIX = torch.tensor ([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [53]:
# Check number of dimensions
MATRIX.ndim

2

In [54]:
MATRIX.shape

torch.Size([2, 2])

In [55]:
#Tensor
TENSOR = torch.tensor ([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [56]:
TENSOR.ndim

3

In [57]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensor
Random Tensor are important because the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data 
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [58]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand (3, 4)
random_tensor

tensor([[0.3326, 0.5841, 0.9024, 0.2639],
        [0.3810, 0.4897, 0.4607, 0.3738],
        [0.9679, 0.4855, 0.6629, 0.9260]])

In [59]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 244, 244)) #height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 244, 244]), 3)

### Zeros and Ones

In [60]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
ones = torch.ones (size= (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
ones.dtype

torch.float32

In [64]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [65]:
#use torch.range()
one_to_ten = torch.arange(start= 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big errors you will run into with pytorch and deep learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [67]:
#Float 32 tensor
float_32_tensor = torch.tensor ([3.0, 6.0, 9.0],
                                dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                                device=None,#what device is your tensor on
                                requires_grad=False) #wheather or not to track gradients with this tensor oprations
float_32_tensor

tensor([3., 6., 9.])

In [68]:
float_32_tensor.dtype

torch.float32

In [69]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [71]:
int_32_tensor = torch.tensor ([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [72]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from tensor (tensor attributes)
1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [73]:
# Create a tensor
some_tensor = torch.rand (3, 4)
some_tensor

tensor([[0.1373, 0.4008, 0.8005, 0.9614],
        [0.5875, 0.5804, 0.9948, 0.8381],
        [0.9607, 0.6258, 0.6507, 0.0623]])

In [74]:
 some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [75]:
 some_tensor.size()

torch.Size([3, 4])

In [76]:
#Find out details about some tensor
print (some_tensor)
print (f"Data type of tensor: {some_tensor.dtype}")
print (f"shape of tensor: {some_tensor.shape}")
print (f"Device tensor is on: {some_tensor.device}")



tensor([[0.1373, 0.4008, 0.8005, 0.9614],
        [0.5875, 0.5804, 0.9948, 0.8381],
        [0.9607, 0.6258, 0.6507, 0.0623]])
Data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)
Tensor opertions include:
    * Addition
    * Subtraction
    * Multiplication (element-wise)
    * Divisoin
    * Matrix multiplication
    

In [77]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [78]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [79]:
tensor

tensor([1, 2, 3])

In [80]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [81]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [82]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
Two main ways of performing multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)
More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html
PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [83]:
#Element wise multiplication
print (tensor, "*" , tensor)
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [84]:
# Matrix multiplication
torch.matmul (tensor, tensor)

tensor(14)

In [85]:
 %%time
 value = 0
 for i in range (len (tensor)) :
     value += tensor [i] * tensor [i]
print (value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [86]:
%%time
torch.matmul (tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning : Shape errors

In [89]:
# Shape for matrix multiplication
tensor_A = torch.tensor ([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor ([[7, 10],
                          [8, 11],
                         [9, 12]])
#tensor.mm (tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's and alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [90]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose** .

A **transpose** switch the axes or dimensions of a given tensor.

In [91]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [92]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [93]:
#The matrix multiplication operation works when tensor_B is transposed
print (f"Original shaoees: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print ("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print (f"\nOutput shape: {output.shape}")

Original shaoees: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [94]:
#Crearte a tensor
x = torch.arange (0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [96]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [97]:
#find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [98]:
# Find the sum
torch.sum(x), x.sum()  

(tensor(450), tensor(450))

### Finding the positional min and max

In [99]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [100]:
#Find the position in tensor that has the minimum valkue with argmin () -> returns index position of that target tensor where the minimum value occurs

x.argmin ()

tensor(0)

In [102]:
# Find teh position in tensor that has the maximum vakue with argmax ()
x.argmax ()

tensor(9)

In [103]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes and input tensor to defined shape
* View - Return a view of and input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a terget tensor
* Permute - Returmn a view of the input with dimensions permuted (swapped) in a certain way

In [104]:
# Lets Create a tensor
import torch
x = torch.arange (1., 10.)
x, x.shape   

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [105]:
# Add an extra dimension 
x_reshaped = x.reshape (1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [106]:
# Changed the view
z = x.view (1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z [:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [108]:
  # Stack tensor on top of each other
  x_stacked = torch.stack ([x, x, x, x], dim=0)
  x_stacked 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
# torch.squeeze() - remove all single dimensions a target tensor
print (f"Previous tensor: {x_reshaped}")
print (f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print (f"\nNew tensor: {x_squeezed}")
print (f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [110]:
# torch.unsqueeze () - adds a single dimension to a target tensor at a specific dim (dimension)
print (f"Previous target: {x_squeezed}")
print (f"Previous shape: {x_squeezed.shape}")
#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze (dim = 0)
print (f"\nNew tensor: {x_unsqueezed}")
print (f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [111]:
# torch.permute - rearrange the dimensions of a target in a specified order
x_original = torch.rand (size = (224, 224, 3)) # [height, width, color_channeles]
# permute the original tensor to rearrange the axis (or dim) order =
x_permuted = x_original.permute(2, 0, 1) #Shifts axis 0->1, 1->2, 2->0
print (f"Previous shape: {x_original.shape}")
print (f"New shape: {x_permuted.shape}") # [color_channels , height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [112]:
x_original [0, 0, 0] = 728218
x_original [0, 0, 0,], x_permuted [0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [113]:
# Create a tensor
import torch
x = torch.arange (1, 10).reshape (1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [114]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [115]:
#lets index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [116]:
# lets index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [117]:
#you can also use ":" to select "all" of a target dimension
x [:, 0]

tensor([[1, 2, 3]])

In [118]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [119]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x [:, 1, 1]

tensor([5])

In [120]:
# Get index 0of 0th and 1st dimension and all values of 2nd dimension
x [0, 0, :]

tensor([1, 2, 3])

In [121]:
# index on x to return 9
print (x [0] [2] [2])
#index on x to return 3, 6, 9
print (x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [122]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### PyTorch tensor & NumPy
NumPy  is a popular scientific Python numerical computing libary

And because of this , PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> ` torch.from_numpy (ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [123]:
#NumPy array to tensor
import torch
import numpy as np
array = np.arange (1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [124]:
# Change the value of array, what will this do to `tensor` ?
array = array
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [125]:
#Tensor to NumPy array
tensor = torch.ones (7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [126]:
# Change the tensor , what happens to `numpy_tensor` ?
tensor = tensor + 1 
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out random)
In Short how a neural network learns:

start with random numbers -> tensor operation -> update numbers to try and make them of the data -> again -> again -> again ...

To reduce the randomness ib Neural ntwork and PyTorch comes the concept of a ***random seed***

Essentially what the random seed does is "flavour" the randomness

In [127]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print (random_tensor_A)
print (random_tensor_B)
print (random_tensor_A == random_tensor_B)

tensor([[0.6516, 0.3955, 0.2624, 0.8669],
        [0.5519, 0.4114, 0.1662, 0.4905],
        [0.3800, 0.9011, 0.5553, 0.3776]])
tensor([[0.4697, 0.7208, 0.3702, 0.6675],
        [0.4149, 0.3341, 0.2060, 0.8101],
        [0.9319, 0.5788, 0.3836, 0.6543]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [128]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed (RANDOM_SEED)
random_tensor_C = torch.rand (3, 4)

torch.manual_seed (RANDOM_SEED)
random_tensor_D = torch.rand (3, 4)

print (random_tensor_C)
print (random_tensor_D)
print (random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


### #Running tensor and PyTorch object on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thansk to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)


In [129]:
# Check GPU
!nvidia-smi

Thu Nov 28 04:06:30 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P8             18W /  320W |    1113MiB /  16376MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [130]:
# Check for GPU access with Pytorch

import torch
torch.cuda.is_available()

True